import { JenisPeriodeRekap } from "@/Pages/Master/MASTER_PeriodeRekapIndexPage";
import { JenisKelamin, StatusAktif, StatusPengajuanPromosi, StatusPernikahan } from "@/types/index";

export type Unit = {
    id: string;
    nama: string;
    keterangan: string;
    created_at: string;
    updated_at: string;
};
export type StatusPegawai = {
    id: string;
    nama: string;
    keterangan: string;
    created_at: string;
    updated_at: string;
};
export type Golongan = {
    id: string;
    nama: string;
    keterangan: string;
    created_at: string;
    updated_at: string;
};
export type Marhalah = {
    id: string;
    nama: string;
    keterangan: string;
    created_at: string;
    updated_at: string;
};
export type Pegawai = {
    id: string;
    username: string;
    password: string;
    nip: string;
    nik: string;
    foto: string | null;
    nama: string;
    jenis_kelamin: JenisKelamin;
    tempat_lahir: string;
    tanggal_lahir: string;
    no_hp: string;
    suku: string;
    alamat: string;
    agama: string;
    status_pernikahan: StatusPernikahan;
    amanah: string;
    amanah_atasan: string;
    kompetensi_quran: string | null;
    sertifikasi: string | null;
    status_aktif: StatusAktif;
    tanggal_masuk: string;
    tanggal_promosi: string | null;
    tanggal_marhalah: string | null;
    bpjs_kesehatan: 0 | 1;
    bpjs_ketenagakerjaan: 0 | 1;
    data_keluarga: string;
    data_pendidikan_formal: string;
    data_pendidikan_non_formal: string;
    data_pengalaman_organisasi: string;
    data_pengalaman_kerja_pph: string;
    data_pengalaman_kerja_non_pph: string;
    keahlian: string | null;
    golongan_id: string | null;
    marhalah_id: string | null;
    status_pegawai_id: string | null;
    unit_id: string | null;
    created_at: string;
    updated_at: string;
};
export type PeriodeRekap = {
    id: string;
    nama: string;
    keterangan: string;
    awal: string;
    akhir: string;
    jenis: JenisPeriodeRekap;
    status: boolean;
    created_at: string;
    updated_at: string;
};
export type RekapPegawai = {
    id: string;
    pegawai_id: string;
    unit_id: string | null;
    golongan_id: string | null;
    status_pegawai_id: string | null;
    marhalah_id: string | null;
    periode_rekap_id: string;
    amanah: string;
    organisasi: string | null;
    gaji: number;
    skill_manajerial: string | null;
    skill_leadership: string | null;
    raport_profesi: string;
    kedisiplinan: string;
    ketuntasan_kerja: string;
    catatan_negatif: string | null;
    prestasi: string | null;
    pembinaan: string | null;
    terverifikasi: boolean;
    created_at: string;
    updated_at: string;
};
export type Admin = {
    id: string;
    nama: string;
    username: string;
    password: string;
    unit_id: string | null;
    created_at: string;
    updated_at: string;
};
export type PengajuanPromosi = {
    id: string;
    nama: string;
    jenis: string;
    unit_id: string;
    admin_id: string | null;
    admin_penyetuju_id: string | null;
    pegawai_id: string;
    asal_id: string;
    asal_type: string;
    akhir_id: string;
    akhir_type: string;
    keterangan: string | null;
    komentar: string | null;
    status_pengajuan: StatusPengajuanPromosi;
    created_at: string;
    updated_at: string;
};
